import type { Beat } from "../../../scripts/cut-clips";

/**
 * СЦЕНАРИЙ «ПЧЕЛОВОД 3: ОПЕКУНСТВО» — смешной перевод на двух фильмах сразу.
 *
 * Кадры «Годзиллы и Конга» (2024) дают эпос и титанов, кадры «Пчеловода» (2024)
 * дают Стетхема, который этот эпос буднично воспитывает. Оба фильма живут в
 * одном ролике: `film` переключается на каждом бите.
 *
 * Приём монтажа: титан и Стетхем никогда не в одном кадре, их связывает только
 * монтажный стык «реплика → реакция». Поэтому Стетхему подобраны планы, где он
 * смотрит вниз или в сторону, а Суко и Конгу — планы, где они смотрят вверх.
 *
 * Кадры найдены по контактным листам (out/<фильм>/sheets/) — индекс действий
 * Gemini на этих фильмах промахивался, а листы читаются глазами и не врут.
 *
 * Порядок сборки:  npm run vo -- BeekeeperKong  →  npm run cut -- BeekeeperKong
 * Длину бита задаёт озвучка; таймкоды немых битов подобраны короткими (1.6–2.5 c),
 * чтобы реакции резали ритм, а не тормозили его.
 *
 * Мат из авторского сценария сохранён в тексте: композиция сама глушит слово и
 * кладёт поверх бип (см. CENSOR_RE в BeekeeperKong.tsx), в субтитре остаются
 * звёздочки. Поэтому в озвучке слово есть, а в ролике его не слышно.
 */
export const SCRIPT: Beat[] = [
  // --- Акт 1. Пафос: титаны идут ------------------------------------------
  {
    id: "b01",
    film: "godzilla-kong",
    start: 3136.0,
    end: 3138.01,
    kind: "quote",
    speaker: "narrator",
    line: "Древнее зло пробудилось.",
    note: "хук: Конг и рыжий Суко идут по Полой Земле",
    originalVolume: 0.3,
    zoom: 0.95,
  },
  {
    id: "b02",
    film: "godzilla-kong",
    start: 2157.0,
    end: 2160.09,
    kind: "quote",
    speaker: "narrator",
    line: "Великие титаны ведут за собой новое поколение.",
    note: "крупная морда Суко — знакомим зрителя с «мелким»",
    originalVolume: 0.25,
    zoom: 0.9,
  },
  {
    id: "b03",
    film: "godzilla-kong",
    start: 4077.0,
    end: 4079.32,
    kind: "quote",
    speaker: "narrator",
    line: "Но они зашли не в тот район.",
    note: "поворот: Конг ревёт в огне, пафос на максимуме перед сломом",
    originalVolume: 0.35,
    zoom: 0.95,
  },

  // --- Акт 2. Стетхем поясняет мелкому ------------------------------------
  {
    id: "b04",
    film: "beekeeper",
    start: 1217.0,
    end: 1220.26,
    kind: "quote",
    speaker: "stetham",
    line: "Эй, рыжий. Передай своему бате.",
    note: "Стетхем в кепке — первый слом пафоса",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b05",
    film: "godzilla-kong",
    start: 4358.9,
    end: 4360.3,
    kind: "action",
    note: "реакция: Суко пучит глаза",
    originalVolume: 0.5,
    zoom: 0.9,
  },
  {
    id: "b06",
    film: "beekeeper",
    start: 1092.0,
    end: 1096.35,
    kind: "quote",
    speaker: "stetham",
    line: "Если тебе где-то не рады в трусах — приди туда без трусов.",
    note: "главная «мудрость» ролика, читается предельно серьёзно",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b07",
    film: "beekeeper",
    start: 2263.2,
    end: 2265.37,
    kind: "quote",
    speaker: "stetham",
    line: "Пусть вообще охуеют.",
    note: "панч под бип",
    originalVolume: 0.12,
    zoom: 1.0,
  },
  {
    id: "b08",
    film: "godzilla-kong",
    start: 3178.8,
    end: 3181.0,
    kind: "action",
    note: "сверчки: Суко тупит, шутка повисает",
    originalVolume: 0.2,
    zoom: 0.9,
  },
  {
    id: "b09",
    film: "beekeeper",
    start: 2217.0,
    end: 2221.05,
    kind: "quote",
    speaker: "stetham",
    line: "Хотя вы и так без трусов. Короче, вы охуели.",
    note: "добивка — второй бип подряд работает как ритм",
    originalVolume: 0.12,
    zoom: 0.95,
  },

  // --- Акт 3. Воспитательный процесс --------------------------------------
  {
    id: "b10",
    film: "godzilla-kong",
    start: 5318.9,
    end: 5320.2,
    kind: "action",
    note: "Суко скалится — огрызается на старшего",
    originalVolume: 0.6,
    zoom: 0.9,
  },
  {
    id: "b11",
    film: "beekeeper",
    start: 5369.0,
    end: 5370.3,
    kind: "action",
    note: "Стетхем блокирует удар — уворот",
    originalVolume: 0.8,
    zoom: 0.95,
  },
  {
    id: "b12",
    film: "beekeeper",
    start: 3668.9,
    end: 3670.4,
    kind: "action",
    note: "КУЛЬМИНАЦИЯ: удар. Оригинальный звук на полную",
    originalVolume: 0.95,
    slow: 1.3,
    zoom: 1.0,
  },
  {
    id: "b13",
    film: "godzilla-kong",
    start: 4998.8,
    end: 5000.3,
    kind: "action",
    note: "Конг с механической лапой — папаша вступается",
    originalVolume: 0.7,
    zoom: 0.95,
  },
  {
    id: "b14",
    film: "beekeeper",
    start: 5903.9,
    end: 5907.85,
    kind: "quote",
    speaker: "stetham",
    line: "Слышь, папаша. Мелкого научи манерам.",
    note: "Стетхем разбит, но говорит буднично — контраст",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b15",
    film: "beekeeper",
    start: 983.0,
    end: 987.35,
    kind: "quote",
    speaker: "stetham",
    line: "Запомни: одна ошибка — и ты ошибся.",
    note: "заход на абсурдную арифметику",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b16",
    film: "beekeeper",
    start: 3655.0,
    end: 3658.31,
    kind: "quote",
    speaker: "stetham",
    line: "А две ошибки — это уже три ошибки.",
    // Кадр выбран по яркости: первый вариант (96:32) в ч/б превращался в
    // сплошное чёрное поле. Здесь лицо выхвачено тёплым светом и переживает
    // grayscale + contrast 1.45.
    note: "ЧЁРНО-БЕЛЫЙ КАДР + бас-дроп (см. bwBeats в defaultProps)",
    originalVolume: 0.12,
    zoom: 1.0,
  },

  // --- Акт 4. Разборка с Годзиллой ----------------------------------------
  {
    id: "b17",
    film: "godzilla-kong",
    start: 6019.0,
    end: 6020.6,
    kind: "action",
    note: "розовая Годзилла выходит — новая угроза",
    originalVolume: 0.6,
    zoom: 0.95,
  },
  {
    id: "b18",
    film: "beekeeper",
    start: 1153.2,
    end: 1154.6,
    kind: "action",
    note: "Стетхем невозмутимо достаёт свой инвентарь",
    originalVolume: 0.5,
    zoom: 0.95,
  },
  {
    id: "b19",
    film: "beekeeper",
    start: 2293.0,
    end: 2295.66,
    kind: "quote",
    speaker: "stetham",
    line: "И ты прикурить пришла, ящерица?",
    note: "обращение к Годзилле как к шпане у подъезда",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b20",
    film: "beekeeper",
    start: 5132.0,
    end: 5134.27,
    kind: "quote",
    speaker: "stetham",
    line: "Запиши себе на хвосте.",
    note: "подводка к финальной мудрости",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b21",
    film: "beekeeper",
    start: 1175.0,
    end: 1178.31,
    kind: "quote",
    speaker: "stetham",
    line: "Если волк молчит — лучше его не перебивай.",
    note: "псевдо-мудрость про волка",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b22",
    film: "beekeeper",
    start: 987.4,
    end: 992.85,
    kind: "quote",
    speaker: "stetham",
    line: "Особенно если этот волк — пчела. А пчела — это я.",
    note: "логика ломается окончательно — на полном серьёзе",
    originalVolume: 0.12,
    zoom: 0.95,
  },

  // --- Акт 5. Финал и главная мудрость ------------------------------------
  {
    id: "b23",
    film: "godzilla-kong",
    start: 6358.9,
    end: 6360.5,
    kind: "action",
    note: "Годзилла и Конг переглядываются — сдались",
    originalVolume: 0.6,
    zoom: 0.95,
  },
  {
    id: "b24",
    film: "godzilla-kong",
    start: 6199.0,
    end: 6200.5,
    kind: "action",
    note: "Суко смотрит преданно — воспитание сработало",
    originalVolume: 0.5,
    zoom: 0.9,
  },
  {
    id: "b25",
    film: "beekeeper",
    start: 1156.0,
    end: 1159.1,
    kind: "quote",
    speaker: "stetham",
    line: "Живи, кайфуй, гуляй, делай что хочешь.",
    note: "Стетхем у ульев — вернулся к своему делу",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b26",
    film: "beekeeper",
    start: 5981.6,
    end: 5983.67,
    kind: "quote",
    speaker: "stetham",
    line: "Главное — не умирай.",
    note: "пауза перед панчлайном",
    originalVolume: 0.12,
    zoom: 0.95,
  },
  {
    id: "b27",
    film: "beekeeper",
    start: 5993.2,
    end: 5995.82,
    kind: "quote",
    speaker: "stetham",
    line: "А если умер — подпишись на канал.",
    note: "финальный панч, дальше плашка «ПЧЕЛОВОД 3»",
    originalVolume: 0.12,
    zoom: 0.95,
  },

  // --- Стингер после плашки -----------------------------------------------
  // Авторская фишка — Стетхем на велосипеде, а титаны везут его ульи — в
  // исходниках не существует и без генерации кадра недостижима. Ближайший
  // честный эквивалент: Конг с Суко покорно бредут вдвоём, а подпись сообщает,
  // кто теперь работает на пасеке.
  {
    id: "b28",
    film: "godzilla-kong",
    start: 3001.5,
    end: 3004.3,
    kind: "action",
    note: "стингер: Суко и Конг стоят рядом и смотрят в камеру + подпись про ульи",
    originalVolume: 0.5,
    zoom: 0.95,
  },
];
