import type { Beat } from "../../../scripts/cut-clips";

/**
 * СЦЕНАРИЙ «Собеседование джуна в 2026» на кадрах «Кровавого спорта» (1988).
 *
 * Реплики — НАШИ, герои говорят голосами из voices.ts (смешной перевод): отбор на
 * турнир превращается в собеседование, разбивание кирпича — в тестовое задание,
 * чемпион турнира — в будущего ментора. Сюжетный движок — нейросеть, которой
 * кандидат втихую решает задачу.
 *
 * Кадры подобраны по индексу действий (data/index/bloodsport/shots.txt), с
 * предпочтением планов без говорящих лиц — там рассинхрон губ незаметен.
 *
 * Порядок сборки:  npm run vo -- JuniorKumite  →  npm run cut -- JuniorKumite
 * Длину бита задаёт озвучка, таймкоды ниже — только точка входа в кадр.
 */
export const SCRIPT: Beat[] = [
  // --- Акт 1. Резюме -----------------------------------------------------
  {
    id: "b01",
    film: "bloodsport",
    start: 1559.9,
    end: 1563.4,
    kind: "quote",
    speaker: "member",
    line: "В резюме пятнадцать лет опыта",
    note: "хук: комиссия читает резюме",
    zoom: 0.9,
  },
  {
    id: "b02",
    film: "bloodsport",
    start: 1564.8,
    end: 1567.0,
    kind: "quote",
    speaker: "tech",
    line: "Фреймворку три года.",
    note: "первая нестыковка",
    zoom: 0.9,
  },
  {
    id: "b03",
    film: "bloodsport",
    start: 1567.2,
    end: 1569.5,
    kind: "quote",
    speaker: "junior",
    line: "Я просто быстро учусь!",
    note: "кандидат выкручивается",
    zoom: 0.85,
  },
  {
    id: "b04",
    film: "bloodsport",
    start: 1577.7,
    end: 1582.2,
    kind: "quote",
    speaker: "tech",
    line: "Решите задачу без интернета",
    note: "поворот: главное условие",
    zoom: 0.9,
  },
  {
    id: "b05",
    film: "bloodsport",
    start: 1583.2,
    end: 1585.2,
    kind: "quote",
    speaker: "junior",
    line: "Без чего, простите?",
    note: "джун в панике",
    zoom: 0.85,
  },

  // --- Акт 2. Тестовое ---------------------------------------------------
  {
    id: "b06",
    film: "bloodsport",
    start: 1587.5,
    end: 1590.0,
    kind: "quote",
    speaker: "member",
    line: "Тестовое: сорок часов",
    note: "стопка кирпичей как объём работы",
    originalVolume: 0.25,
  },
  {
    id: "b07",
    film: "bloodsport",
    start: 1632.0,
    end: 1634.0,
    kind: "quote",
    speaker: "junior",
    line: "А оплата будет?",
    note: "наивный вопрос",
  },
  {
    id: "b08",
    film: "bloodsport",
    start: 1846.0,
    end: 1848.0,
    kind: "quote",
    speaker: "hr",
    line: "Опыт! Бесценный опыт!",
    note: "ответ, который слышал каждый",
    zoom: 0.9,
  },
  {
    id: "b09",
    film: "bloodsport",
    start: 1634.2,
    end: 1636.7,
    kind: "quote",
    speaker: "junior",
    line: "Нейросеточка, миленькая, выручай",
    note: "герой закрывает глаза — идеальный план под шёпот",
  },
  {
    id: "b10",
    film: "bloodsport",
    start: 1648.6,
    end: 1651.8,
    kind: "action",
    note: "КУЛЬМИНАЦИЯ: удар, кирпич в пыль. Замедление + громкий оригинал",
    slow: 1.5,
    originalVolume: 0.9,
    zoom: 0.9,
  },

  // --- Акт 3. Разоблачение -----------------------------------------------
  {
    id: "b11",
    film: "bloodsport",
    start: 1658.2,
    end: 1659.4,
    kind: "quote",
    speaker: "member",
    line: "Решил за две секунды",
    note: "изумление комиссии",
    zoom: 0.9,
  },
  {
    id: "b12",
    film: "bloodsport",
    start: 1659.4,
    end: 1663.4,
    kind: "quote",
    speaker: "tech",
    line: "Подозрительно чисто.",
    note: "первое подозрение",
  },
  {
    id: "b13",
    film: "bloodsport",
    start: 1663.6,
    end: 1666.5,
    kind: "quote",
    speaker: "tech",
    line: "И комментарии на английском.",
    note: "улика",
    zoom: 0.9,
  },
  {
    id: "b14",
    film: "bloodsport",
    start: 1666.8,
    end: 1668.8,
    kind: "quote",
    speaker: "junior",
    line: "Это авторский стиль!",
    note: "отчаянное оправдание",
  },

  // --- Акт 4. Оффер ------------------------------------------------------
  {
    id: "b15",
    film: "bloodsport",
    start: 1850.0,
    end: 1852.0,
    kind: "quote",
    speaker: "hr",
    line: "Берём! Сто тысяч.",
    note: "неожиданный оффер",
    zoom: 0.85,
  },
  {
    id: "b16",
    film: "bloodsport",
    start: 1685.0,
    end: 1687.0,
    kind: "quote",
    speaker: "junior",
    line: "В месяц?",
    note: "надежда",
  },
  {
    id: "b17",
    film: "bloodsport",
    start: 1888.0,
    end: 1890.0,
    kind: "quote",
    speaker: "hr",
    line: "В год. Зато печеньки!",
    note: "панч про оффер",
    zoom: 0.9,
  },

  // --- Акт 5. Ментор -----------------------------------------------------
  {
    id: "b18",
    film: "bloodsport",
    start: 1678.9,
    end: 1681.4,
    kind: "quote",
    speaker: "chief",
    line: "Я твой ментор.",
    note: "холодная ухмылка чемпиона",
  },
  {
    id: "b19",
    film: "bloodsport",
    start: 2313.9,
    end: 2316.9,
    kind: "quote",
    speaker: "chief",
    line: "Я тоже сижу на нейросети",
    note: "разворот: все так делают",
  },
  {
    id: "b20",
    film: "bloodsport",
    start: 2386.0,
    end: 2388.0,
    kind: "quote",
    speaker: "chief",
    line: "Только никому.",
    note: "жест пальцем у носа — идеально ложится",
  },
  {
    id: "b21",
    film: "bloodsport",
    start: 550.1,
    end: 552.5,
    kind: "quote",
    speaker: "tech",
    line: "Можешь идти.",
    note: "финальная отбивка",
  },
];
